Numpy Arrays

In [2]:
import numpy as np

In [4]:
data1 = [3.6, 6, 2, 1] # list
arr1 = np.array(data1)

In [6]:
arr1

array([3.6, 6. , 2. , 1. ])

In [7]:
data2 = (4, 5, 3.2, 7) # tuple
arr2 = np.array(data2)

In [8]:
arr2

array([4. , 5. , 3.2, 7. ])

In [9]:
arr1.ndim # massiv o'lchovini aniqlash

1

In [10]:
arr2.ndim # massiv o'lchovini aniqlash

1

In [11]:
data3 = [[2, 3, 1.2], [8, 1, 0.5]] # list ichidagi list (nested list)
arr3 = np.array(data3)

In [18]:
arr3.ndim

2

In [14]:
data4 = [[1, 2, 3], [4, 5, 7], [0, 2.4, 9]] # nested list
arr4 = np.array(data4)

In [15]:
arr4

array([[1. , 2. , 3. ],
       [4. , 5. , 7. ],
       [0. , 2.4, 9. ]])

In [19]:
arr4.ndim

2

shape va size metodlari:

In [21]:
arr4.shape # qator va ustunlar sonini ko'rsatish (n, m)

(3, 3)

In [22]:
arr4.size # mavjud barcha elementlar sonini qaytarish

9

zeros va ones metodlari yordamida massivlar yaratish

In [23]:
arr5 = np.zeros((3, 4)) # (3, 4) o'lchamdagi nollar bilan to'ldirilgan massiv yaratish
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
arr6 = np.ones((2, 3)) # (2, 3) o'lchamdagi birlar bilan to'ldirilgan massiv yaratish
arr6

array([[1., 1., 1.],
       [1., 1., 1.]])

arange metodidan foydalanib yaratish

In [25]:
arr7 = np.arange(3, 15, 2) # 3 dan 15 gacha sonlarni 2 qadam bilan massivga joylab borish
arr7 

array([ 3,  5,  7,  9, 11, 13])